# Generated by Django 5.2.6 on 2025-09-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='orgernizer',
            new_name='orgenizer',
        ),
    ]
