# Generated by Django 5.2.6 on 2025-09-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_orgernizer_event_orgenizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Ticket Type', 'verbose_name_plural': 'Ticket Types'},
        ),
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('event', 'name')},
        ),
    ]
