# Generated by Django 5.2.6 on 2025-09-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_tickettype_options_tickettype_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='orgenizer',
            new_name='organizer',
        ),
    ]
