# Generated by Django 5.2.6 on 2025-09-26 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 9, 51, 7, 52919)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2025, 9, 26, 9, 51, 7, 52975)),
        ),
    ]
