# Generated by Django 5.2.6 on 2025-09-26 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_start_date_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 9, 56, 40, 797099)),
        ),
    ]
