# Generated by Django 5.2.6 on 2025-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_ticket_ticket_code_alter_event_id_alter_ticket_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='stripe_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
