# Generated by Django 5.2.6 on 2025-09-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_ticket_event_remove_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Paid'), ('R', 'Refunded'), ('F', 'Failed'), ('FRE', 'Free')], default='P', max_length=3),
        ),
    ]
