# Generated by Django 5.2.6 on 2025-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_ticket_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='max_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
