# Generated by Django 5.2.6 on 2025-09-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_tickettype_max_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
