# Generated by Django 5.2.6 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_ticket_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
