# Generated by Django 5.2.6 on 2025-10-03 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_ticket_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
