# Generated by Django 5.2.6 on 2025-10-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_ticket_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
